import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Template from "./template";

export const metadata: Metadata = {
  title: "Stephen Gift Dada",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <main>{children}</main>
      </body>
    </html>
  );
}
